openapi: 3.0.1
info:
  title: Nightbot
  version: '0.1'
  description: defaultDescription
  license:
    name: MIT
    url: https://github.com/nightbot/api-docs/blob/master/LICENSE
servers:
  - url: https://api.nightbot.tv/
paths:
  /1/channel:
    get:
      operationId: GetChannel
      description: ''
      security:
        - oAuth2AuthCode:
            - channel
        - oAuth2Implicit:
            - channel
  /1/channel/join:
    post:
      operationId: JoinChannel
      description: ''
      security:
        - oAuth2AuthCode:
            - channel
        - oAuth2Implicit:
            - channel
  /1/channel/part:
    post:
      operationId: PartChannel
      description: ''
      security:
        - oAuth2AuthCode:
            - channel
        - oAuth2Implicit:
            - channel
  /1/channel/send:
    post:
      operationId: SendChannelMessage
      description: ''
      security:
        - oAuth2AuthCode:
            - channel_send
        - oAuth2Implicit:
            - channel_send
  /1/commands:
    get:
      operationId: GetСustomСommands
      description: ''
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
    post:
      operationId: AddNewСustomСommand
      description: ''
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
  /1/commands/{id}:
    get:
      operationId: GetСustomСommandById
      description: ''
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
    put:
      operationId: EditСustomСommandById
      description: ''
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
    delete:
      operationId: DeleteСustomСommandById
      description: ''
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
  /1/commands/default:
    get:
      operationId: GetDefaultСommands
      description: ''
      security:
        - oAuth2AuthCode:
            - commands_default
        - oAuth2Implicit:
            - commands_default
  /1/commands/default/{name}:
    get:
      operationId: GetDefaultСommandByName
      description: ''
      security:
        - oAuth2AuthCode:
            - commands_default
        - oAuth2Implicit:
            - commands_default
    put:
      operationId: EditDefaultСommandByName
      description: ''
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
  /1/me:
    get:
      description: ''
      operationId: GetСurrentUser
      security:
        - oAuth2AuthCode: []
        - oAuth2Implicit: []
  /1/regulars:
    get:
      description: ''
      operationId: GetRegulars
      security:
        - oAuth2AuthCode:
            - commands
        - oAuth2Implicit:
            - commands
    post:
      description: ''
      operationId: AddNewRegular
      security:
        - oAuth2AuthCode:
            - regulars
        - oAuth2Implicit:
            - regulars
  /1/regulars/{id}:
    get:
      description: ''
      operationId: GetRegularById
      security:
        - oAuth2AuthCode:
            - regulars
        - oAuth2Implicit:
            - regulars
    delete:
      description: ''
      operationId: DeleteRegularById
      security:
        - oAuth2AuthCode:
            - regulars
        - oAuth2Implicit:
            - regulars
  /1/song_requests:
    get:
      description: ''
      operationId: GetSongRequestSettings
      security:
        - oAuth2AuthCode:
            - song_requests
        - oAuth2Implicit:
            - song_requests
    put:
      description: ''
      operationId: EditSongRequestSettings
      security:
        - oAuth2AuthCode:
            - song_requests
        - oAuth2Implicit:
            - song_requests
  /1/song_requests/playlist:
    get:
      description: ''
      operationId: GetPlaylist
      security:
        - oAuth2AuthCode:
            - song_requests_playlist
        - oAuth2Implicit:
            - song_requests_playlist
    post:
      description: ''
      operationId: AddNewPlaylistItem
      security:
        - oAuth2AuthCode:
            - song_requests_playlist
        - oAuth2Implicit:
            - song_requests_playlist
    delete:
      description: ''
      operationId: ClearPlaylist
      security:
        - oAuth2AuthCode:
            - song_requests_playlist
        - oAuth2Implicit:
            - song_requests_playlist
  /1/song_requests/playlist/import:
    post:
      description: ''
      operationId: ImportRemotePlaylist
      security:
        - oAuth2AuthCode:
            - song_requests_playlist
        - oAuth2Implicit:
            - song_requests_playlist
  /1/song_requests/playlist/{id}:
    get:
      description: ''
      operationId: GetPlaylistItemById
      security:
        - oAuth2AuthCode:
            - song_requests_playlist
        - oAuth2Implicit:
            - song_requests_playlist
    delete:
      description: ''
      operationId: DeletePlaylistItemById
      security:
        - oAuth2AuthCode:
            - song_requests_playlist
        - oAuth2Implicit:
            - song_requests_playlist
  /1/song_requests/queue:
    get:
      description: ''
      operationId: GetQueue
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
    post:
      description: ''
      operationId: AddNewQueueItem
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
    delete:
      description: ''
      operationId: ClearQueue
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
  /1/song_requests/queue/play:
    post:
      description: ''
      operationId: ResumeCurrentQueueItem
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
  /1/song_requests/queue/pause:
    post:
      description: ''
      operationId: PauseCurrentQueueItem
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
  /1/song_requests/queue/skip:
    post:
      description: ''
      operationId: SkipCurrentQueueItem
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
  /1/song_requests/queue/{id}:
    get:
      description: ''
      operationId: GetQueueItemById
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
    delete:
      description: ''
      operationId: DeleteQueueItemById
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
  /1/song_requests/queue/{id}/promote:
    post:
      description: ''
      operationId: PromoteQueueItemById
      security:
        - oAuth2AuthCode:
            - song_requests_queue
        - oAuth2Implicit:
            - song_requests_queue
  /1/spam_protection:
    get:
      description: ''
      operationId: GetFilters
      security:
        - oAuth2AuthCode:
            - spam_protection
        - oAuth2Implicit:
            - spam_protection
  /1/spam_protection/{type}:
    get:
      description: ''
      operationId: GetFilterByType
      security:
        - oAuth2AuthCode:
            - spam_protection
        - oAuth2Implicit:
            - spam_protection
    put:
      description: ''
      operationId: EditFilterByType
      security:
        - oAuth2AuthCode:
            - spam_protection
        - oAuth2Implicit:
            - spam_protection
  /1/subscribers:
    get:
      description: ''
      operationId: GetSubscribers
      security:
        - oAuth2AuthCode:
            - subscribers
        - oAuth2Implicit:
            - subscribers
    post:
      description: ''
      operationId: AddNewSubscriber
      security:
        - oAuth2AuthCode:
            - subscribers
        - oAuth2Implicit:
            - subscribers
  /1/subscribers/{id}:
    get:
      description: ''
      operationId: GetSubscriberById
      security:
        - oAuth2AuthCode:
            - subscribers
        - oAuth2Implicit:
            - subscribers
    delete:
      description: ''
      operationId: DeleteSubscriberById
      security:
        - oAuth2AuthCode:
            - subscribers
        - oAuth2Implicit:
            - subscribers
  /1/timers:
    get:
      description: ''
      operationId: GetTimers
      security:
        - oAuth2AuthCode:
            - timers
        - oAuth2Implicit:
            - timers
    post:
      description: ''
      operationId: AddNewTimer
      security:
        - oAuth2AuthCode:
            - timers
        - oAuth2Implicit:
            - timers
  /1/timers/{id}:
    get:
      description: ''
      operationId: GetTimerById
      security:
        - oAuth2AuthCode:
            - timers
        - oAuth2Implicit:
            - timers
    put:
      description: ''
      operationId: EditTimerById
      security:
        - oAuth2AuthCode:
            - timers
        - oAuth2Implicit:
            - timers
    delete:
      description: ''
      operationId: DeleteTimerById
      security:
        - oAuth2AuthCode:
            - timers
        - oAuth2Implicit:
            - timers
components:
  securitySchemes:
    oAuth2AuthCode:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: /oauth2/authorize
          tokenUrl: /oauth2/token
          refreshUrl: /oauth2/token
          scopes:
            channel: View and edit channel settings and join/part the bot
            channel_send: Ability to send messages to the channel as Nightbot
            commands: View, add, edit, and remove channel custom commands
            commands_default: View, edit, enable, and disable channel default commands
            regulars: View, add, and remove channel regulars
            song_requests: View and edit channel song request settings
            song_requests_queue: >-
              View, add, edit, and remove songs on the channel song request
              queue
            song_requests_playlist: >-
              View, add, edit, and remove songs on the channel song request
              playlist
            spam_protection: View, edit, enable, and disable channel spam protection filters
            subscribers: >-
              View, add, and remove channel subscribers (useful for third party
              subscription services)
            timers: View, add, edit, and remove channel timers
    oAuth2Implicit:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: /oauth2/authorize
          scopes:
            channel: View and edit channel settings and join/part the bot
            channel_send: Ability to send messages to the channel as Nightbot
            commands: View, add, edit, and remove channel custom commands
            commands_default: View, edit, enable, and disable channel default commands
            regulars: View, add, and remove channel regulars
            song_requests: View and edit channel song request settings
            song_requests_queue: >-
              View, add, edit, and remove songs on the channel song request
              queue
            song_requests_playlist: >-
              View, add, edit, and remove songs on the channel song request
              playlist
            spam_protection: View, edit, enable, and disable channel spam protection filters
            subscribers: >-
              View, add, and remove channel subscribers (useful for third party
              subscription services)
            timers: View, add, edit, and remove channel timers
